### PR TITLE
chore: add back py all reduce for testing purpose

### PR DESCRIPTION
**Pull request by samsja**

### CODE REVIEW

**Comment by Jackmin801** [comment]
What do you think about adding the python collectives back rather than removing the tests? The tests work with the python collectives present and give us information about the error caused by the quantization relative to hivemind.

It is also used by the all_reduce_test.py benchmark script to make sure the new one is faster

**Comment by Jackmin801** [comment]
https://github.com/PrimeIntellect-ai/prime/pull/58/files#diff-e1661ca6c2f518b5b7b2954a744e07b835d3fab2adfdaf3cb0d3cccb44a6af80

**Comment by samsja** [comment]
> https://github.com/PrimeIntellect-ai/prime/pull/58/files#diff-e1661ca6c2f518b5b7b2954a744e07b835d3fab2adfdaf3cb0d3cccb44a6af80

sure I will add back

**Comment by samsja** [comment]
> > https://github.com/PrimeIntellect-ai/prime/pull/58/files#diff-e1661ca6c2f518b5b7b2954a744e07b835d3fab2adfdaf3cb0d3cccb44a6af80
> 
> sure I will add back

Should I add to the test only ?

**Comment by Jackmin801** [comment]
Well its used by the benchmark script as well so youd have to add it in two places

**Review by Jackmin801 — APPROVED** [review]
Nice! lgtm

**Pull request merged**
